# ── Prefix Key ─────────────────────────
unbind C-b
set -g prefix C-a
bind C-a send-prefix

#bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# ── General Settings ─────────────────────
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ── Shortcut ─────────────────────
# Vi Copy Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ── TPM Plugin Manager ──────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'jabirali/tmux-tilish'
set -g @tilish-default 'main-vertical'

set -g @plugin 'eduwass/tmux-palette'
set -g @palette-key 'C-p'

set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme "bru/espresso"

# Plugin initialization is expensive on Termux.  Load it in the background so
# creating or attaching to a session is not blocked by theme/plugin setup.
run -b '~/.tmux/plugins/tpm/tpm'
#run '~/.tmux/plugins/tpm/tpm'
