gui:
  scrollHeight: 10 # how many lines you scroll by
  theme:
    selectedLineBgColor:
      - '#174525'
git:
  diffRenderers:
    - colorarg: always
      command: delta --dark --paging=never
      autoRefresh: false
