#!/usr/bin/env sh

# Description: Simple script to remove files

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

xargs -0 -a "$sel" -I % rm -vfr %

# Clear selection
if [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
