# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

#: Fonts {{{

font_size 14.0

#: }}}

#: Cursor customization {{{

cursor_blink_interval 0

#: }}}

#: Scrollback {{{

# scrollback_lines 2000

# 1024 MB / per scrollback pager
# view scrollback by
#   show_scrollback
#   show_first_command_output_on_screen
#   show_last_command_output
#   show_last_non_empty_command_output
#   show_last_visited_command_output
scrollback_pager_history_size 1024

#: }}}

#: Performance tuning {{{

repaint_delay 100

#: }}}

#: Scrolling {{{

# map ctrl+shift+g show_last_command_output
# map ctrl+shift+h show_scrollback
# map ctrl+shift+z scroll_to_prompt -1
# map ctrl+shift+x scroll_to_prompt 1

#: }}}

#: Select and act on visible text {{{

# map ctrl+shift+e open_url_with_hints
# map ctrl+shift+p>f kitten hints --type path --program -
# map ctrl+shift+p>l kitten hints --type line --program -
# map ctrl+shift+p>w kitten hints --type word --program -
# map ctrl+shift+p>y kitten hints --type hyperlink
map ctrl+shift+p>shift+w kitten hints --type word --program @
map ctrl+shift+p>shift+l kitten hints --type line --program @

#: }}}

#: Miscellaneous {{{

# map ctrl+shift+f5 load_config_file
# map ctrl+shift+f6 debug_config
# map ctrl+shift+f2 edit_config_file

#: }}}

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
